spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/news
    username: newsapp
    password: newsapp
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  redis:
    host: 0.0.0.0
    port: 6389